import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    Flex,
    Spacer,
    Heading,
    Input,
    Button,
    Box,
    useColorModeValue,
    useColorMode} from '@chakra-ui/react'
import {useState} from 'react';
import {IoSunny, IoMoon } from 'react-icons/io5'

export default function Home() {
    const {toggleColorMode} =useColorMode();
    // const {formBackGround} = useColorModeValue("gray.100", "gray.700");
    const formBackGround = useColorModeValue("gray.100", "gray.700")
    const [toggle, setToggle] = useState(false);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex
                height={"150vh"}
                alignItems={"center"}
                justifyContent={"center"}
            >
                <Flex
                    direction={"column"}
                    background={formBackGround}
                    p={12}
                    rounded={6}
                    position={"relative"}
                >
                    <Heading mb={6}>Log In</Heading>
                    <Input
                        placeholder="Votre email..."
                        variant={"filled"}
                        mb={8}
                        type="email"
                    />
                    <Input
                        placeholder="**************"
                        variant={"filled"}
                        type="password"
                        mb={7}
                    />
                    <Button colorScheme={"teal"}>Log in</Button>
                    <Box
                        position={"absolute"}
                        top={2}
                        right={2}
                        cursor={"pointer"}
                        onClick={() => {
                            toggleColorMode();
                            setToggle(!toggle)

                        }}
                    >
                        {/*<IoSunny/>*/}
                        {toggle? <IoMoon/> :  <IoSunny/> }
                    </Box>
                </Flex>
            </Flex>
            {/*<main className={styles.main}>*/}
            {/*<h1 className={styles.title}>*/}
            {/*Hello! and Welcome to <a href="https://nextjs.org">Next.js!</a>*/}
            {/*</h1>*/}

            {/*<p className={styles.description}>*/}
            {/*Get started by editing{' '}*/}
            {/*<code className={styles.code}>pages/index.tsx</code>*/}
            {/*</p>*/}

            {/*<div className={styles.grid}>*/}
            {/*<a href="https://nextjs.org/docs" className={styles.card}>*/}
            {/*<h2>Documentation &rarr;</h2>*/}
            {/*<p>Find in-depth information about Next.js features and API.</p>*/}
            {/*</a>*/}

            {/*<a href="https://nextjs.org/learn" className={styles.card}>*/}
            {/*<h2>Learn &rarr;</h2>*/}
            {/*<p>Learn about Next.js in an interactive course with quizzes!</p>*/}
            {/*</a>*/}

            {/*<a*/}
            {/*href="https://github.com/vercel/next.js/tree/canary/examples"*/}
            {/*className={styles.card}*/}
            {/*>*/}
            {/*<h2>Examples &rarr;</h2>*/}
            {/*<p>Discover and deploy boilerplate example Next.js projects.</p>*/}
            {/*</a>*/}

            {/*<a*/}
            {/*href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*target="_blank"*/}
            {/*rel="noopener noreferrer"*/}
            {/*className={styles.card}*/}
            {/*>*/}
            {/*<h2>Deploy &rarr;</h2>*/}
            {/*<p>*/}
            {/*Instantly deploy your Next.js site to a public URL with Vercel.*/}
            {/*</p>*/}
            {/*</a>*/}
            {/*</div>*/}
            {/*</main>*/}

            {/*<footer className={styles.footer}>*/}
            {/*<a*/}
            {/*href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
            {/*target="_blank"*/}
            {/*rel="noopener noreferrer"*/}
            {/*>*/}
            {/*Powered by{' '}*/}
            {/*<span className={styles.logo}>*/}
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
            {/*</span>*/}
            {/*</a>*/}
            {/*</footer>*/}
        </div>
    )
}
