// import Head from 'next/head'
// import TeacherDesign from '../src/front/TeacherDesign';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// // import {}
//
// export default function Home() {
//     return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//         <TeacherDesign/>
//         <main className={styles.main}>
//         </main>
//     </div>
//   )
// }

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    Flex, Box
    } from '@chakra-ui/react'
import {useState} from 'react';
import {IoSunny, IoMoon } from 'react-icons/io5'
import Blog from '../src/components/Blog';
import Details from '../src/components/Details';
export default function Home() {
    const [toggle, setToggle] = useState(false);

    return (
        <Box bg={"white"} w="100%">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*<Blog/>*/}
            <Details/>
        </Box>
    )
}
